name: Build Geode Mod (iOS)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: iOS Build
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/cli/.github/actions/setup@main

      - name: Build Mod for iOS
        run: |
          geode profile add --platform ios GithubActions
          geode sdk install-binaries
          geode mod build --platform ios
