name: Build Geode Mod (iOS)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: iOS Build
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Mod for iOS
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          target: iOS
